# Configuração do AntiVPN

# Mensagem para jogadores usando VPN
kick-message: "§cVPN detectada! Por favor, desative sua VPN para jogar."

# Escolha qual API de verificação utilizar (proxycheck, iphub)
primary-api: "proxycheck"
fallback-api: "iphub"

# Cache para evitar consultas repetidas (em segundos)
# 86400 segundos = 24 horas
# Impede verificações de VPN repetidas para o mesmo IP dentro de 24 horas
cache-time: 86400

# Intervalo para limpeza do cache (em minutos)
# 1440 minutos = 24 horas
# Remove entradas de cache desatualizadas uma vez por dia
cache-cleanup-interval: 1440

# Logs de conexões detectadas como VPN
enable-logs: true

# Limite de tentativas por API antes de mudar para fallback
api-retry-limit: 3

# Configurações das APIs
api:
  proxycheck:
    enabled: true
    api-key: "YOUR_PROXYCHECK_API_KEY"
    # Deixe em branco para usar versão gratuita

  iphub:
    enabled: true
    api-key: "YOUR_IPHUB_API_KEY"

# Whitelist de IPs (que serão ignorados na verificação)
ip-whitelist:
  - "127.0.0.1"
  - "192.168.1.1"

# Lista de apelidos permitidos (nicks que serão ignorados na verificação)
nicknames-whitelist:
  - "Steve"
  - "Alex"